services:
  nginx-proxy:
    container_name: namex-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  django-app:
    container_name: django-app
    build: .
    command: sh -c "gunicorn --config gunicorn_config.py project.wsgi:application"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /var/www/static/:/var/www/static/
    env_file:
      - .env
    networks:
      - nginx-network
    depends_on:
      - nginx-proxy

networks:
  nginx-network:
    driver: bridge
    attachable: true
